### ISSUE TITLE
temporal queue

### ISSUE THREAD

**Issue by tyui592** [tyui592/awesome-precipitation-nowcasting#2]
* Latent diffusion models for generative precipitation nowcasting with accurate uncertainty quantification
* arXiv (2023), https://arxiv.org/abs/2304.12891

**Comment by tyui592** [comment]
LATENT DIFFUSION MODELS FOR GENERATIVE PRECIPITATION
NOWCASTING WITH ACCURATE UNCERTAINTY QUANTIFICATION

**Comment by tyui592** [comment]
* EarthArXiv: https://eartharxiv.org/repository/about/

**Comment by IncubatorShokuhou** [comment]
repo: https://github.com/MeteoSwiss/ldcast
